# Imagen base
FROM node:20

# Crear el directorio de la app
WORKDIR /app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto (ajústalo según el que uses en Express)
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "start"]